### ISSUE TITLE
Very big image files.

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/fin-ucd-lib-deployment#1]
For the Eastman dataset, we identified problems using the original uncompressed tif images, as they were much larger than what were used in the application.  The most up to date version of the loris IIIF server has an additional check for compressed images that compress to very large sizes.  This is described in this related [Issue](https://stackoverflow.com/questions/25705773/image-cropping-tool-python#:~:text=Warning%3A%20To%20protect%20against%20potential,is%20over%20a%20certain%20limit.) 

The current punjabi site has a small number of images that fail this test.  For example, the [thumbnail image](https://next.dams.library.ucdavis.edu/fcrepo/rest/collection/pioneering-punjabis/D-643/d3t30x/media/images/d3t30x-1269.jpg/svc:iiif/full/500,406/0/default.jpg)   for the collection. 

Investigation of the logs show this error:  
``` text
loris_1           |   File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2724, in _decompression_bomb_check
loris_1           |     "could be decompression bomb DOS attack." % (pixels, 2 * MAX_IMAGE_PIXELS)
loris_1           | DecompressionBombError: Image size (466095438 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```
 
Updates to this parameter are available in the [Configuration](https://github.com/loris-imageserver/loris/blob/01df4d4be08336459ba24a15415c82f495d279c6/doc/configuration.md), but the first question is do we want to?  Should we encourage better image organization, but allow massive images, or this is this a good warning not be be using the original images.

**Comment by qjhart** [comment]
@jrmerz .  @EricNebeker  and I discussed this on Friday.  Eric's happy to add Web friendly images to the few Punjabi images that need them.  After thinking about this for awhile.  My inclination is that we probably should *not* make this fix, and instead have some hard limiits on the size of the images we use.  I wonder what your take is?

**Comment by qjhart** [comment]
@EricNebeker, the general concensus is that the current MAX_IMAGE_PIXELS is a pretty good guard for the website, and we should encourage the use of we ready images.  So, we are going to close this w/out a fix.  Let me know if you want an issue pulled for the Punjabi collection directly?

**Comment by EricNebeker** [comment]
@qjhart I'll reformat those images. Thanks.
